/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-10-29 09:55:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import hardware.Server;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>Test for the front end</title>\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("      html,body{\n");
      out.write("        margin:0px;\n");
      out.write("        padding:0px;\n");
      out.write("      }\n");
      out.write("      #test{\n");
      out.write("        float:left;\n");
      out.write("        color: #eee;\n");
      out.write("        background-color: #008000;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 50px;\n");
      out.write("        padding: 20px;\n");
      out.write("      }\n");
      out.write("      .rack{\n");
      out.write("        float:left;\n");
      out.write("        width: 400px;\n");
      out.write("        height: 546px;\n");
      out.write("        background: url('rack.jpg');\n");
      out.write("        margin: 50px;\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      #sysinfo{\n");
      out.write("      \tposition:absolute;\n");
      out.write("      \ttop:140px;\n");
      out.write("      \tleft:970px;\n");
      out.write("      \tbackground-color:#369;\n");
      out.write("      \theight:120px;\n");
      out.write("      \twidth:150px;\n");
      out.write("      \tpadding-left:20px;\n");
      out.write("      \t\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      #rackinner1{\n");
      out.write("        float:left;\n");
      out.write("        width:280px;\n");
      out.write("        height:380px;\n");
      out.write("        margin-top: 45px;\n");
      out.write("        margin-left: 45px;\n");
      out.write("        padding-left: 15px;\n");
      out.write("        padding-top: 15px;\n");
      out.write("        overflow:scroll;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      #rackinner2{\n");
      out.write("        float:left;\n");
      out.write("        width:280px;\n");
      out.write("        height:380px;\n");
      out.write("        margin-top: 45px;\n");
      out.write("        margin-left: 45px;\n");
      out.write("        padding-left: 15px;\n");
      out.write("        padding-top: 15px;\n");
      out.write("        overflow:scroll;\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      #info{\n");
      out.write("        float: left;\n");
      out.write("        width: 100%;\n");
      out.write("        height: 200px;\n");
      out.write("        color: #eee;\n");
      out.write("        background-color: #222;\n");
      out.write("        padding: 10px;\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("      }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("    ");
 
    
    //This initiates 8 different server objects
    Server one =new Server();
    Server two =new Server();
    Server three =new Server();
    Server four =new Server();
    Server five =new Server();
    Server six =new Server();
    Server seven=new Server();
    Server eight =new Server();
    eight.resetCounter();
    
      out.write("\n");
      out.write("\t//These arrays hold the power information for each server\n");
      out.write("    var serverID = [\"");
      out.print(one.getID());
      out.write("\", \"");
      out.print(two.getID());
      out.write("\", \"");
      out.print(three.getID());
      out.write("\", \"");
      out.print(four.getID());
      out.write("\", \"");
      out.print(five.getID());
      out.write("\", \"");
      out.print(six.getID());
      out.write("\", \"");
      out.print(seven.getID());
      out.write("\", \"");
      out.print(eight.getID());
      out.write("\"];\n");
      out.write("    var max = [\"");
      out.print(one.getMax());
      out.write("\", \"");
      out.print(two.getMax());
      out.write("\", \"");
      out.print(three.getMax());
      out.write("\", \"");
      out.print(four.getMax());
      out.write("\", \"");
      out.print(five.getMax());
      out.write("\", \"");
      out.print(six.getMax());
      out.write("\", \"");
      out.print(seven.getMax());
      out.write("\", \"");
      out.print(eight.getMax());
      out.write("\"];\n");
      out.write("    var average = [\"");
      out.print(one.getAverage());
      out.write("\", \"");
      out.print(two.getAverage());
      out.write("\", \"");
      out.print(three.getAverage());
      out.write("\", \"");
      out.print(four.getAverage());
      out.write("\", \"");
      out.print(five.getAverage());
      out.write("\", \"");
      out.print(six.getAverage());
      out.write("\", \"");
      out.print(seven.getAverage());
      out.write("\", \"");
      out.print(eight.getAverage());
      out.write("\"];\n");
      out.write("\n");
      out.write("    var images = 8;\n");
      out.write("    \n");
      out.write("   \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    //This displays the server info\n");
      out.write("    function displayServerInfo(element, number){\n");
      out.write("    document.getElementById(\"sysinfo\").innerHTML=\"<p>Server Number: \"+parseInt(serverID[number])+\"</p><p>Max Power: \"+max[number]+\"</p><p>Average: \"+average[number]+\"</p>\";\n");
      out.write("    \n");
      out.write("    var elements = document.getElementsByName(\"server\");\n");
      out.write("    \n");
      out.write("    for(var i=0; i<elements.length; i++) {\n");
      out.write("\t\telements.item(i).style.opacity=\"1.0\";\n");
      out.write("     \n");
      out.write("    }\n");
      out.write("   \n");
      out.write("    element.style.opacity = \"0.2\";\n");
      out.write("    element.style.filter  = 'alpha(opacity=90)'; // IE fallback\n");
      out.write("    \n");
      out.write("   \n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("    function drag(ev) {\n");
      out.write("        ev.dataTransfer.setData(\"text/html\", ev.target.id);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function drop(ev) {\n");
      out.write("        ev.preventDefault();\n");
      out.write("        \n");
      out.write("        var data = ev.dataTransfer.getData(\"text/html\");\n");
      out.write("        ev.target.appendChild(document.getElementById(data));\n");
      out.write("\n");
      out.write("        images--;\n");
      out.write("        //change();\n");
      out.write("        //alert(\"server added to rack 2\" + this);\n");
      out.write("    }\n");
      out.write("  \n");
      out.write("    function allowDrop(ev) {\n");
      out.write("        ev.preventDefault();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function change() {\n");
      out.write("      var stuff = \"\";\n");
      out.write("      for (var i = 0; i < images; i++) {\n");
      out.write("          stuff += \"<img src='server.jpg' id='drag' draggable='true' ondragstart='drag(event)' />\";\n");
      out.write("      };\n");
      out.write("      //alert(\"innerHTML\" + stuff);\n");
      out.write("      document.getElementById(\"rackinner1\").innerHTML = stuff;\n");
      out.write("    }\n");
      out.write("    </script>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("    <div id=\"test\">Racks and Servers</div>\n");
      out.write("\n");
      out.write("    <div class=\"rack\">\n");
      out.write("      <div id=\"rackinner1\"  ondrop=\"drop(event)\" ondragover=\"allowDrop(event)\">\n");
      out.write("        <img name=\"server\" onClick=\"displayServerInfo(this, 0)\" src=\"server.jpg\" id=\"drag0\" draggable=\"true\" ondragstart=\"drag(event)\"/>\n");
      out.write("        <img name=\"server\" onClick=\"displayServerInfo(this,1)\" src=\"server.jpg\" id=\"drag1\" draggable=\"true\" ondragstart=\"drag(event)\" />\n");
      out.write("        <img name=\"server\" onClick=\"displayServerInfo(this,2)\" src=\"server.jpg\" id=\"drag2\" draggable=\"true\" ondragstart=\"drag(event)\" />        \n");
      out.write("        <img name=\"server\" onClick=\"displayServerInfo(this,3)\" src=\"server.jpg\" id=\"drag3\" draggable=\"true\" ondragstart=\"drag(event)\" />\n");
      out.write("        <img name=\"server\" onClick=\"displayServerInfo(this,4)\" src=\"server.jpg\" id=\"drag4\" draggable=\"true\" ondragstart=\"drag(event)\" />\n");
      out.write("        <img name=\"server\" onClick=\"displayServerInfo(this,5)\" src=\"server.jpg\" id=\"drag5\" draggable=\"true\" ondragstart=\"drag(event)\" /> \n");
      out.write("        <img name=\"server\" onClick=\"displayServerInfo(this,6)\" src=\"server.jpg\" id=\"drag6\" draggable=\"true\" ondragstart=\"drag(event)\" />\n");
      out.write("        <img name=\"server\" onClick=\"displayServerInfo(this,7)\" src=\"server.jpg\" id=\"drag7\" draggable=\"true\" ondragstart=\"drag(event)\" />\n");
      out.write("        </div>\n");
      out.write("     \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <div class=\"rack\">\n");
      out.write("      <div id=\"rackinner2\" ondrop=\"drop(event)\" ondragover=\"allowDrop(event) \">\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"sysinfo\"></div>\n");
      out.write("\n");
      out.write("    <div id=\"info\"> </div>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
